spring:
  kafka:
    bootstrap-servers:
      - localhost:9092
      - localhost:9093
      - localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: 1
#      retries: 10
#      properties:
#        enable.idempotence: true
#        max.in.flight.requests.per.connection: 5
#      linger: 10                 # ms
#      batch-size: 32768          # bytes
#      compression-type: lz4
#      buffer-memory: 33554432    # 32MB
